# Generated by Django 3.2.5 on 2021-07-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
