# Generated by Django 3.2.5 on 2021-07-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210719_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createaccountandmailstudent',
            options={'verbose_name': 'Create Account and Mail Student', 'verbose_name_plural': 'Create Account and Mail Student'},
        ),
    ]
