# Generated by Django 3.2.5 on 2021-07-04 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the category', max_length=50, verbose_name='Name of Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter the name of the candidate', max_length=50, verbose_name='Name of Candidate')),
                ('picture', models.ImageField(help_text='Upload the image of the candidate', upload_to='candidates/pictures/', verbose_name='Picture of Candidate')),
                ('number_of_votes', models.PositiveIntegerField(default=0, verbose_name='Number of Votes')),
                ('upvote', models.BooleanField(default=False)),
                ('category', models.ForeignKey(help_text='Select the category the candidate belongs to', on_delete=django.db.models.deletion.CASCADE, to='vote_app.category')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
            },
        ),
    ]
