# Generated by Django 3.2.5 on 2021-07-04 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='category',
            field=models.ForeignKey(help_text='Select the category the candidate belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='vote_app.category'),
        ),
    ]
