# Generated by Django 3.2.5 on 2021-07-05 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0005_alter_candidate_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='upvote',
        ),
    ]
