# Generated by Django 3.2.5 on 2021-07-08 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote_app', '0006_remove_candidate_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='voters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
