# Generated by Django 3.2.5 on 2021-07-08 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote_app', '0007_category_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='voters',
        ),
        migrations.AddField(
            model_name='category',
            name='voters',
            field=models.ManyToManyField(related_name='voted_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
