# Generated by Django 3.2.5 on 2021-07-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0010_alter_candidate_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter your full name', max_length=50, verbose_name='Full Name')),
                ('student_id', models.CharField(help_text='Enter your ID', max_length=20, verbose_name='Student ID')),
                ('email_address', models.EmailField(help_text='Enter your email address', max_length=300, null=True, verbose_name='Email Address')),
                ('message', models.TextField(help_text='Enter your message', max_length=1000, verbose_name='Complaint')),
            ],
            options={
                'verbose_name': 'Support Form',
                'verbose_name_plural': 'Support Forms',
            },
        ),
    ]
