# Generated by Django 3.2.5 on 2021-07-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0014_candidate_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='no',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Nos'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='yes',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Number of Yeses'),
        ),
    ]
