# Generated by Django 3.2.5 on 2021-07-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0015_auto_20210725_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='vetting_score',
            field=models.FloatField(default=0, help_text="Enter the score the candidate had at vetting, please don't include the percentage sign", verbose_name='Vetting Score'),
        ),
    ]
